쇼팟 장르 컴포저블과 홈 화면의 메뉴 바 컴포저블 구현
YAPP-Github/24th-App-Team-3-Android pull request #14
Opened 2024-07-16 14:09 UTC by HyeonSeok7

### :wrench: 관련 이슈

### :clipboard: 변경 내용

- 쇼팟 아티스트 컴포저블 구현
- 쇼팟 메뉴 바 컴포저블 구현

### :rocket: 테스트 방법

1. showpot-deign을 빌드하고 실행합니다.
2. 새로 추가된 기능을 사용해 봅니다.
4. 수정된 기능이 올바르게 동작하는지 확인합니다.
5. 기존의 모든 기능이 정상적으로 동작하는지 확인합니다.

### :computer: 변경 사항

Compo
- `ComponentsPreview.kt` 아티스트 관련 컴포저블 추가
- `ComponentsPreview.kt`에 홈 화면 메뉴 컴포저블 추가

### :white_check_mark: 체크리스트

- [ ] 코드가 의도한 대로 작동하는지 확인했습니다.
- [ ] 새로운 기능에 대한 테스트를 추가했습니다.
- [ ] 기존의 모든 테스트가 통과했습니다.
- [ ] 코드 스타일 가이드라인을 준수했습니다.
- [ ] 문서가 업데이트되었습니다 (필요한 경우).

### :memo: 추가 정보

- `ComponentsPreview.kt` 아티스트 3번째 버튼 -> `ShowPotArtistSubscription` 클릭하면 선택/미선택 기능의 버튼

2024-07-16 14:27 UTC, HyeonSeok7 commented
https://github.com/user-attachments/assets/801a6503-9a86-4e32-8635-2c999e3c7082
PR 게시글 작성때 **누락된** 동작 영상 첨부

2024-07-18 06:17 UTC, soopeach requested changes
다음부터 저희 컴포저블들 사진도 pr에 같이 올리면 좋을 것 같아요!!
 이름만 보고는 뭔지 알기가 생각보다 쉽지않군요!
 ㅋㅋㅋㅋ 컴포저블들이 많다보니까

2024-07-18 06:17 UTC, soopeach commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/component/ShowPotMenu.kt
> +fun ShowPotMenu(
메뉴가 혹시 그 탑바 영역인가요???
메뉴라는 이름과 탑바의 역할이 뭔가 잘 매치가 안되서 변경하면 좋을 것 같아요

2024-07-18 08:58 UTC, HyeonSeok7 commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/component/ShowPotMenu.kt
> +fun ShowPotMenu(
@soopeach 
이거.. 이름을 어떻게 지엉야할지 고민하다가 
우선, 만들어 놓고 상의해야겠다해서 피그마에 있는 이름 따와서했어
이름 괜찮으걸로 수정해서 머지해줘

2024-07-18 11:02 UTC, merged