홈 화면 티켓 구현
YAPP-Github/24th-App-Team-3-Android pull request #21
Opened 2024-07-29 14:29 UTC by HyeonSeok7

## 🤘 작업 내용
- 티켓 컴포저블 구현 

## 💻 동작 화면
<img width="281" alt="image" src="https://github.com/user-attachments/assets/7a5b39bf-b4fb-4c79-bc4b-edb3e87bca82">

2024-07-30 12:38 UTC, soopeach requested changes
충돌난거 해결해주세요!

그 후에 어프로브 할게용

2024-07-30 12:38 UTC, soopeach commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/component/ShowPotTicket.kt
> +fun ShowPotTicket(
저희 이미지 페인터를 쓸 일이 없어서.. 요것도 나중에 다 바꿔야합니다!
근데 지금 페인터 쓰는 것 보다 미리 그냥 url로 만들어 두는게 편하지 않을까요??

2024-07-30 12:38 UTC, soopeach commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/component/ShowPotTicket.kt
> +    showTimeTextColor: Color = ShowpotColor.MainYellow,
얘는 고정값 안 넣어줘도 괜찮을 것 같은데 어떻게 생각하세요?

2024-07-30 12:38 UTC, soopeach commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/component/ShowPotTicket.kt
> +                    overflow = TextOverflow.Ellipsis,
요거 두 개를 고정값으로 주는게 낫겠네요

2024-07-30 12:38 UTC, soopeach commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/preview/ComponentsPreview.kt
> +                ),
요거 그라데이션 해당 컴포저블에서 고정값은데 밖으로 빼서 사용한 이유가 있으신가요?
바뀌지 않는 값인데, 요런식으로 빼면 매번 불필요한 작업을 하게되는 것으로 보여서요

2024-07-30 12:48 UTC, HyeonSeok7 commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/component/ShowPotTicket.kt
> +    showTimeTextColor: Color = ShowpotColor.MainYellow,
얍 뺐음

2024-07-30 12:48 UTC, HyeonSeok7 commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/component/ShowPotTicket.kt
> +fun ShowPotTicket(
컴포즈에서 Url 로드 하는 방법 아직 안해봐서
우선, 만들자가 1차 목표였어서 저렇게 했었음

2024-07-30 12:50 UTC, HyeonSeok7 commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/preview/ComponentsPreview.kt
> +                ),
나중에 다른 그라데이션이 생길 수도 있다고 생각해서 
재활용해서 사용하려고 하려고한 의도인데
다른게 생기면 그때 수정이 나을 것 같다는거지?

2024-07-30 13:22 UTC, merged

2024-07-31 05:19 UTC, soopeach commented on core/designsystem/src/main/java/com/alreadyoccupiedseat/designsystem/preview/ComponentsPreview.kt
> +                ),
네네 아마 안생길 가능성이 더 높아보여서요!